[package]
name = "mini_notes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
chrono = "0.4"
flexi_logger = "0.23"
log = "0.4"
